name: clean_architecture_tdd_course
description: TDD Clean Architecture for Flutter

version: 1.0.0+1

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport:
    git: https://github.com/jpnurmi/flutter_libserialport

  # Service locator
  get_it: ^7.1.3
  # Bloc for state management
  flutter_bloc: ^7.0.1
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.9.2
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.13.3
  # Local cache
  shared_preferences: ^2.0.6
  datetime_picker_formfield: ^2.0.0
  protobuf: ^2.0.0
  crclib: ^2.0.0
  libserialport: ^0.2.0+2
  bitsdojo_window: ^0.1.1+1
  hex: ^0.2.0
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10

flutter:
  uses-material-design: true
